name: Deploy Watcher and Airflow
on:
  workflow_dispatch:

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: inbox-ai-456015
        export_default_credentials: true

    - name: Configure VM environment and files
      env:
        WATCHER_ENV: ${{ secrets.WATCHER_ENV }}
        AIRFLOW_ENV: ${{ secrets.AIRFLOW_ENV }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud compute ssh kcap-assessment-prod --zone=us-east1-c --command="bash -s" <<EOF
          set -e

          echo "Installing system dependencies..."
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose unzip curl gnupg wget

          echo "Installing Google Chrome..."
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome.deb
          rm google-chrome.deb

          echo "Cloning repo..."
          git clone https://github.com/Prad06/press-release-summerizer.git

          echo "Creating .env files..."
          mkdir -p ~/press-release-summerizer/config
          
          # Root .env (Watcher)
          cat <<EOT > ~/press-release-summerizer/.env
        $WATCHER_ENV
        EOT

          # Airflow .env
          cat <<EOT > ~/press-release-summerizer/airflow/.env
        $AIRFLOW_ENV
        EOT

          # Google credentials.json
          cat <<EOT > ~/press-release-summerizer/config/credentials.json
        $GOOGLE_CREDENTIALS
        EOT

          # Service account json
          cat <<EOT > ~/press-release-summerizer/config/google_sa.json
        $GCP_SA_KEY
        EOT

          echo "Setting airflow/downloads to 777..."
          chmod 777 ~/press-release-summerizer/airflow/downloads

          echo "VM environment is fully set up."
        EOF

