name: Deploy on VM for Press Release Summarizer
on:
  workflow_dispatch:
jobs:
  setup-environment:
    name: Setup Environment on VM
    runs-on: self-hosted
    steps:
    - name: Set up directory permissions
      run: |
        sudo chown -R $(whoami):$(whoami) ${{ github.workspace }}
        sudo chmod -R 755 ${{ github.workspace }}
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Make config directory
      run: |
        sudo mkdir -p config
        sudo chown -R $(whoami) config

    - name: Create dynamic credentials.json file
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}
        dir: "config/"

    - name: Create dynamic google_service_account.json file
      id: create-json-2
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "google_sa.json"
        json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        dir: "config/"

    - name: Create .env file
      run: |
        echo "${{ secrets.AIRFLOW_ENV }}" > airflow/.env
        echo "${{ secrets.WATCHER_ENV }}" > .env

    - name: Copy all the files to the VM
      run: |
        sudo cp -r ${{ github.workspace }}/* $HOME/
        sudo chown -R $(whoami):$(whoami) $HOME/*
        sudo chmod -R 755 $HOME/*

    - name: Create a download directory
      run: |
        sudo mkdir -p $HOME/airflow/downloads
        sudo chown -R $(whoami):$(whoami) $HOME/airflow/downloads

    - name: Docker Compose Up for Airflow
      run: |
        cd $HOME/airflow
        sudo docker compose --build
        sudo docker compose run airflow-init
        sudo docker compose up -d

        echo "Airflow is getting ready..."
    
    - name: Docker Compose Up for Watcher
      run: |
        cd $HOME
        sudo docker compose --build
        sudo docker compose up -d

        echo "Watcher is getting ready..."

    - name: Health Check for Airflow
      run: |
        sleep 30
        while ! curl -s http://localhost:8080/health; do
          echo "Waiting for Airflow to be healthy..."
          sleep 5
        done
        echo "Airflow is healthy!"

