name: Deploy on VM for Press Release Summarizer
on:
  workflow_dispatch:
jobs:
  setup-environment:
    name: Setup Environment on VM
    runs-on: self-hosted
    steps:
    - name: Set up directory permissions
      run: |
        sudo chown -R $(whoami):$(whoami) ${{ github.workspace }}
        sudo chmod -R 755 ${{ github.workspace }}
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Docker, Compose, and Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose unzip curl gnupg wget

        echo "Installing Google Chrome..."
        wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome.deb
        rm google-chrome.deb

        sudo systemctl enable docker
        sudo systemctl start docker

    - name: Make config directory
      run: |
        sudo mkdir -p config
        sudo chown -R $(whoami) config

    - name: Create dynamic credentials.json file
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}
        dir: "config/"

    - name: Create dynamic google_service_account.json file
      id: create-json-2
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "google_sa.json"
        json: ${{ secrets.GCP_SA_KEY }}
        dir: "config/"

    - name: Copy all the files to the VM
      run: |
        sudo mkdir -p $HOME/press-release-summarizer
        sudo cp -r ${{ github.workspace }}/* $HOME/press-release-summarizer/
        sudo chown -R $(whoami):$(whoami) $HOME/press-release-summarizer/*
        sudo chmod -R 755 $HOME/press-release-summarizer/*

    - name: Create .env files in final destination
      run: |
        sudo chown -R $(whoami) $HOME/press-release-summarizer
        echo "${{ secrets.WATCHER_ENV }}" > $HOME/press-release-summarizer/.env
        echo "${{ secrets.AIRFLOW_ENV }}" > $HOME/press-release-summarizer/airflow/.env    


    - name: Create a download directory
      run: |
        sudo mkdir -p $HOME/press-release-summarizer/airflow/downloads
        sudo chown -R $(whoami):$(whoami) $HOME/press-release-summarizer/airflow/downloads

    - name: Docker Compose Up for Airflow
      run: |
        cd $HOME/press-release-summarizer/airflow
        sudo docker-compose build
        sudo docker-compose run airflow-init
        sudo docker-compose up -d

        echo "Airflow is getting ready..."
    
    - name: Docker Compose Up for Watcher
      run: |
        cd $HOME/press-release-summarizer
        sudo docker-compose build
        sudo docker-compose up -d

        echo "Watcher is getting ready..."

    - name: Health Check for Airflow
      run: |
        sleep 30
        while ! curl -s http://localhost:8080/health; do
          echo "Waiting for Airflow to be healthy..."
          sleep 5
        done
        echo "Airflow is healthy!"

