name: Deploy on VM for Press Release Summarizer
on:
  workflow_dispatch:
jobs:
  setup-environment:
    name: Setup Environment on VM
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Make config directory
      run: |
        sudo mkdir -p config
        sudo chown -R $(whoami) config

    - name: Create dynamic credentials.json file
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}
        dir: "config/"

    - name: Create dynamic google_service_account.json file
      id: create-json-2
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "google_sa.json"
        json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        dir: "config/"

    - name: Create .env file
      run: |
        sudo chown -R $(whoami) $HOME/airflow
        echo "${{ secrets.AIRFLOW_ENV }}" > $HOME/airflow/.env
        cat $HOME/airflow/.env

        sudo chown -R $(whoami) $HOME
        echo "${{ secrets.WATCHER_ENV }}" > $HOME/.env
        cat $HOME/.env

    - name: Docker Compose Up for Airflow
      run: |
        sudo docker compose -f $HOME/airflow/docker-compose.yml --build
        sudo docker compose -f $HOME/airflow/docker-compose.yml run airflow-init
        sudo docker compose -f $HOME/airflow/docker-compose.yml up -d

        echo "Airflow is getting ready..."
    
    - name: Docker Compose Up for Watcher
      run: |
        sudo docker compose -f $HOME/docker-compose.yml --build
        sudo docker compose -f $HOME/airflow/docker-compose.yml up -d

        echo "Watcher is getting ready..."

    - name: Health Check for Airflow
      run: |
        sleep 30
        while ! curl -s http://localhost:8080/health; do
          echo "Waiting for Airflow to be healthy..."
          sleep 5
        done
        echo "Airflow is healthy!"

