name: Deploy on VM for Press Release Summarizer
on:
  workflow_dispatch:
jobs:
  setup-environment:
    name: Setup Environment on VM
    runs-on: self-hosted
    steps:
    - name: Set up directory permissions
      run: |
        sudo chown -R $(whoami):$(whoami) ${{ github.workspace }}
        sudo chmod -R 755 ${{ github.workspace }}

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Docker, Compose, and Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose unzip curl gnupg wget

        echo "Installing Google Chrome..."
        wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome.deb
        rm google-chrome.deb

        sudo systemctl enable docker
        sudo systemctl start docker
        sleep 10  # Wait for Docker to fully start

    - name: Create required directories
      run: |
        sudo mkdir -p config
        sudo mkdir -p $HOME/press-release-summarizer/airflow/{logs,plugins,downloads}
        sudo chown -R $(whoami):$(whoami) config
        sudo chown -R $(whoami):$(whoami) $HOME/press-release-summarizer
        sudo chmod -R 777 $HOME/press-release-summarizer/airflow/{logs,plugins,downloads}

    - name: Create dynamic credentials files
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}
        dir: "config/"

    - name: Create dynamic google_service_account.json file
      id: create-json-2
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "google_sa.json"
        json: ${{ secrets.GCP_SA_KEY }}
        dir: "config/"

    - name: Clean up old docker containers
      run: |
        sudo docker system prune -a --volumes -f

    - name: Copy files to the VM
      run: |
        sudo mkdir -p $HOME/press-release-summarizer
        sudo cp -r ${{ github.workspace }}/* $HOME/press-release-summarizer/
        sudo chown -R $(whoami):$(whoami) $HOME/press-release-summarizer/*
        sudo chmod -R 777 $HOME/press-release-summarizer/*

    - name: Create .env files
      run: |
        echo "${{ secrets.WATCHER_ENV }}" > $HOME/press-release-summarizer/.env
        echo "${{ secrets.AIRFLOW_ENV }}" > $HOME/press-release-summarizer/airflow/.env
        chmod 644 $HOME/press-release-summarizer/.env
        chmod 644 $HOME/press-release-summarizer/airflow/.env

    - name: Initialize Airflow
      run: |
        cd $HOME/press-release-summarizer/airflow
        sudo docker-compose build
        sudo docker-compose up airflow-init
        sudo docker-compose up -d
        echo "Waiting for Airflow to initialize..."
        sleep 30

    - name: Health Check for Airflow
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8080/health; then
            echo "Airflow is healthy!"
            exit 0
          fi
          echo "Waiting for Airflow to be healthy... Attempt $i"
          sleep 10
        done
        echo "Airflow health check failed"
        exit 1

    - name: Start Watcher Service
      run: |
        cd $HOME/press-release-summarizer
        sudo docker-compose build
        sudo docker-compose up -d
        echo "Watcher is getting ready..."