name: Provision VM for Press Release Summarizer

on:
  workflow_dispatch:

jobs:
  deploy-vm:
    name: Create Airflow VM & Firewall
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: inbox-ai-456015
        export_default_credentials: true

    - name: Make deploy.sh executable
      run: chmod +x deploy.sh

    - name: Run deployment script
      id: deploy
      run: ./deploy.sh

    - name: Fetch and display VM external IP
      run: |
        echo "Fetching external IP address for the VM..."
        EXTERNAL_IP=$(gcloud compute instances describe kcap-assessment-prod \
          --zone=us-east1-c \
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

        echo ""
        echo "External IP address for kcap-assessment-dev: $EXTERNAL_IP"
        echo "::set-output name=external_ip::$EXTERNAL_IP"
